workdir: "v2/sample_tests_ni"
reaction:
  name: "Pd Heck coupling"
  type: oxidative_addition
  tags: [heck, aryl-halide, oxidative-addition]

reactants:
  - id: catalyst
    type: organometallic
    metal:
      element: Ni
      oxidation_state: 0
      spin: 0
      coordination: 2
      geometry: linear
    ligands:
      - name: pph3
        count: 2

  - id: substrate
    type: xyz
    xyz: ar_br.xyz
    reactive_centers:
      - atom_idx: 1
        partner_idx: 0
        plane_indices: [1, 2, 3, 4, 5, 6]
        site_type: aryl_CBr

settings:
  sample_size: 10
  bond_formation:
    atom_pairs:
      - [catalyst, substrate]
    distance_scale: 1.75
  optimization:
    optimizer: "BFGS"

calculators:
  gfn1:
    engine: DXTB
    options:
      method: GFN1
      spin: 0

pipeline:
  - id: preopt-reactants
    action: relax-reactants
    calc: gfn1
    fmax: 0.02
  - id: sample-space
    action: bi-sample
    sample: 10
  - id: after-sample-relax
    action: relax
    calc: gfn1
    fmax: 0.2
    steps: 100
    filters:
      - name: energy_force
        args:
          e_cutoff: 40
          fmax_cutoff: 10.0
          e_min: auto
  - id: walk-dock
    action: walk
    calc: gfn1
    steps: 25
    fmax: 0.5
    moves:
      - id: pull-ipso-c
        kind: pair_pull
        pair:
          a: catalyst:0
          b: substrate:1
        k: 10
        target:
          from: auto
          to: 3.0
          step: 0.1
      - id: pull-br
        kind: pair_pull
        pair:
          a: catalyst:0
          b: substrate:0
        k: 20
        target:
          from: auto
          to: 3.2
          step: 0.1
  - id: walk-tug
    action: walk
    calc: gfn1
    steps: 100
    fmax: 0.3
    moves:
      - id: pull-ipso-c
        kind: pair_pull
        pair:
          a: catalyst:0
          b: substrate:1
        k: 20
        target:
          from: auto
          to: auto
          step: 0.025
      - id: pull-br
        kind: pair_pull
        pair:
          a: catalyst:0
          b: substrate:0
        k: 20
        target:
          from: auto
          to: auto
          step: 0.025
      - id: push-br-from-ipso-c
        kind: tether_pull
        pair:
          a: substrate:1
          b: substrate:0
        k: 20
        offset:
          from: auto
          to: 2.9
          step: 0.025
  
  # - name: "ORCA"
  #   steps: 10
  #   options:
  #     command: "orca"
  #     charge: 0
  #     mult: 1
  #     orcasimpleinput: 'r2SCAN-3c TightSCF ENGRAD'
  #     orcablocks: '%pal nprocs 10 end'
  #     task: "gradient"
  #     directory: 'orca'
